mod eight;
mod eighteen;
mod eighty_five;
mod eighty_four;
mod eighty_two;
mod fifty;
mod fifty_eight;
mod fifty_five;
mod fifty_two;
mod four;
mod fourteen;
mod fourty_eight;
mod fourty_four;
mod fourty_six;
mod fourty_three;
mod fourty_two;
mod one;
mod seven;
mod seventy;
mod seventy_eight;
mod seventy_five;
mod seventy_nine;
mod seventy_six;
mod seventy_two;
mod sixteen;
mod sixty_four;
mod sixty_nine;
mod sixty_one;
mod sixty_seven;
mod sixty_three;
mod ten;
mod thirty_eight;
mod thirty_four;
mod thirty_two;
mod three;
mod twelve;
mod twenty;
mod twenty_eight;
mod twenty_four;
mod twenty_seven;
mod twenty_six;
mod twenty_two;
mod two;

fn main() {
    eighty_five::main();
}
