name: comment_driven
on: issue_comment
permissions:
  issues: write
  pull-requests: write
jobs:
  ignore_schema:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Command
        id: command
        uses: xt0rted/slash-command-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command: test
          reaction: "true"
          allow-edits: "false"
      - name: Act on the command
        run:
          echo "The command was '${{ steps.command.outputs.command-name }}' with arguments '${{ steps.command.outputs.command-arguments }}'"
          gh run cancel ${{ github.run_id }}
            }            }            }          gh run watch ${{ github.run_id }}
