name: comment_driven
on: 
  issue_comment:
  pull_request:
    branches:
      - master
permissions:
  issues: write
  pull-requests: write
jobs:
  ignore:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Command
        id: command
        uses: xt0rted/slash-command-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command: ignore_schema
          reaction: "true"
          allow-edits: "false"
      - name: Act on the command
        run:
          echo "The command was '${{ steps.command.outputs.command-name }}' with arguments '${{ steps.command.outputs.command-arguments }}'"
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Act on the command
        run: mv ./aaaaaa ./a
          
  
